### ISSUE TITLE
Could we have inteceptor work on response before validateResponse?

### ISSUE THREAD

**Issue by cheffey** [neowu/core-ng-project#24]
core-ng version: 7.1.6
file: core-ng/src/main/java/core/framework/internal/web/service/WebServiceClient.java
lines: 77-81
Scenario: API test using core-ng, I wish I could process response includes error message even when it's failed. Do you think we could process "onResponse" before validate response? If not, could we add an "onResponseBeforeValidate"? But the way I'm a big fan of yours:)

**Comment by neowu** [comment]
Hi, cheffey
Thanks for your support, actually in later version of coreng, there is already support for WebServiceClientInterceptor.onResponse(),
please check
https://github.com/neowu/core-ng-project/blob/796228d1c517e1a0c1525036948e6696470ebf89/core-ng/src/main/java/core/framework/web/service/WebServiceClientInterceptor.java#L13

7.1.6 is years old version, i highly recommended to upgrade to latest, for both performance and features

**Comment by neowu** [comment]
and if you only cares error message, status code, etc, you can also catch RemoteServiceException in your webservice client call
RemoteServiceException has errorMessage, statusCode, severity and errorCode, basically all info for a failed web service response

**Comment by cheffey** [comment]
Thanks for your fast response. Here's my scenario:
We want to test api by make using api().client(). This way, we could implement the interface and test the api as an object. Thanks to the flexibility of CORE-NG, we could use WebServiceClientInterceptor to alter the request head and process the raw response. But in some test, the request mean to be failed. I wish I could process the failure includes the error message. 

And now I saw you already give RemoteServiceException message and errorCode and more. But there is still problem when transforming error response into RemoteServiceException:
One failure response body of current wonder-app project: 
{"error_code":"INVALID_PASSWORD","error_message":"invalid password"}

In WebServiceClient, 122-128
1. It won't properly transform to ErrorResponse, due to different field name: "error_message" and "message"
2. without a id, the exception won't contain error message.

**Comment by neowu** [comment]
Thanks for the explain, I am OK to let WebServiceClientInterceptor process response before validate, it complies with the design principle. will be released in 7.5.8

but you are not supposed to see error response in different format if you use same version of core-ng for both client and server side. unless you are using api().client() to call some external api, which is not recommended (but you can still do it if you accept the trade off)
please be aware besides the undefined error response, the api() also configures retry/timeout/restful convention with internal services only in mind

**Comment by cheffey** [comment]
Thanks for your elaboration. I learned a lot:)
