### ISSUE TITLE
[Support Request] XHR request may read cache by browser which conflict the purpose of ajax request

### ISSUE THREAD

**Issue by cheffey** [neowu/core-ng-project#30]
The scenario is that:
The project is a react project. Page A has a list and an edit button.
1. click the edit button to page B.
2. edit the list and click save.
3. the browser makes a put request to update the list and wait for it to finish.
4. Then the browser goes back to Page A automatically.
5. Page A makes a get request to get the list. And that request is read from the cache, so the list displayed as NOT updated.

This issue is likely that could be resolved by the frontend eventually. My question is that should backend response allow the browser to cache ajax requests in the first place?

**Comment by neowu** [comment]
i am not aware of any ajax response is cached in react application, 
so for 5), can you clarify whether page A never send ajax request when goes back, or page sent request (you can see it thru chrome dev tools network), but it got cached (dev tool will show memory cache or disk cache in size column)?
and check whether server side sends any cache-control header? (not supposed to have)

**Comment by cheffey** [comment]
I confirmed that the API request triggered by backing-up action was used with disk cached. The frontend fixed this bug. I will try to recreate this bug by writing a react demo, if I can do so I will reopen this issue.

**Comment by neowu** [comment]
ok, please update me if you are able to reproduce, 

i did quick test, if there is no cache-control header in response, i don't see chrome caches the xhr get request, 
i think you may want to double check the response header of the cached ajax call.

if cache-control: no-store is needed (usually you want to add this header for index.html response)
then you can still do it via interceptor, but i haven't encountered any cases like what you said
