### ISSUE TITLE
Provide Relative Path on REST Request 

### ISSUE THREAD

**Issue by james-novino** [neowu/core-ng-project#48]
Currently, from the perspective of any HTTP interceptor in core-ng, there is no way to get access to the relative path without the path parameters. There are currently two properties on the `Request` interface in core-ng related to paths: 

- https://github.com/neowu/core-ng-project/blob/d7c6dafe5155dbf6e8218fc54b3a05c7def64255/core-ng/src/main/java/core/framework/web/Request.java#L12
- https://github.com/neowu/core-ng-project/blob/d7c6dafe5155dbf6e8218fc54b3a05c7def64255/core-ng/src/main/java/core/framework/web/Request.java#L18

The `path` parameter is currently the original path without decoding for instance `api/object/767e963b-f6f8-4d26-b49f-1636d95db854/details` instead of `api/object/:id/details`. There also doesn't appear to be a good way to get to the decode version of this path from the perspective of the Request since that is only accessible through the `Path` class which is only accessible at the registering of the service: 

- https://github.com/neowu/core-ng-project/blob/d7c6dafe5155dbf6e8218fc54b3a05c7def64255/core-ng/src/main/java/core/framework/module/APIConfig.java#L67

**Comment by neowu** [comment]
Hi, James

We have Request.pathParam() method to retrieve the value of path pattern, 

https://github.com/neowu/core-ng-project/blob/d7c6dafe5155dbf6e8218fc54b3a05c7def64255/core-ng/src/main/java/core/framework/web/Request.java#L24

the reason to provides undecoded path() and requestURL() is that, during troubleshooting or logging context, we want to know what exactly request the client sends.

and in action log, framework puts "path_pattern" in action_log.context.path_pattern

and even we return path pattern from Request, it's can't be used directly without parsing, 

what's your use case of Request.pathPattern();

**Comment by neowu** [comment]
if you just want to get this info and pass to somewhere
you can retrieve it by
```

ActionLogContext.get("path_pattern").get(0)

```

**Comment by james-novino** [comment]
Are requests always executed on a single thread?

**Comment by neowu** [comment]
Yes, action is always within same thread
