### ISSUE TITLE
这个框架是否有bean初始化的接口，在完成bean创建后需要执行一些初始化方法

### ISSUE THREAD

**Issue by Echo-miao** [neowu/core-ng-project#57]
这个框架是否有bean初始化的接口，在完成bean创建后需要执行一些初始化方法，是否可以像Spring框架一样，加一个Initialization接口，可以在Bean初始化后执行初始化方法

**Comment by neowu** [comment]
因为框架的的设计原则是：维护大于第一次开发，所以希望从module里可以看到完整的构造/依赖关系，
如果想初始化代码，可以在module里用类似写法
```java
GoogleKMS kms = bind(new GoogleKMS(requiredProperty("app.google.kms.key.prefix")));
onStartup(kms::initialize);
```

**Comment by Echo-miao** [comment]
好的，感谢解答
