### ISSUE TITLE
为何不用注解扫描向BeanFactory里面放bean，

### ISSUE THREAD

**Issue by Echo-miao** [neowu/core-ng-project#58]
看到大部分是通过core.framework.impl.inject.BeanFactory#bind的方法向BeanFactory的beans属性放bean，为何不直接在要注册bean的类上面标一个注解，通过注解扫描的方式向BeanFactory里面放Bean呢，通过bind的方式注册Bean，不会觉得代码侵入性很大吗

**Comment by neowu** [comment]
因为框架的的设计原则是：维护大于第一次开发，所以希望从module里可以看到完整的构造/依赖关系，显式>隐式，这也是IOC的理念，另外在module里bind，和代码侵入有什么关系？你的业务代码还是标准的DI下的写法

**Comment by Echo-miao** [comment]
好的，感谢解答
