### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by linxu** [neowu/core-ng-project#7]
can you improve the core-ng wiki?

**Comment by neowu** [comment]
yes, i will do if i have some time, which part do you particular interested in?

**Comment by linxu** [comment]
Using tutorials and technical principles.
I want to improve my level through this framework!

**Comment by neowu** [comment]
ok, i will add something from next week, btw, have you checked this project? 
https://github.com/neowu/core-ng-demo-project

**Comment by linxu** [comment]
yes, i have checked out.

**Comment by neowu** [comment]
I start to add few wiki pages, you know as developer, no one enjoys to write doc :) , how about
1) do you have any particular questions? I will answer and put in corresponding wiki section?
2) do you want to contribute in wiki as well?

**Comment by linxu** [comment]
I particular in the principle of framework design and  how to use
I'd like to contribute, if I can :)

**Comment by neowu** [comment]
for design principle, there is https://github.com/neowu/core-ng-project/wiki/Design

do you have more specific question? if your question is general, then you may wait long until I put info you interested.

**Comment by linxu** [comment]
Nothing，thanks for your reply！
Where do you work?

**Comment by neowu** [comment]
Do you know me in person? you can contact me by neowu.us@gmail.com
I am currently in China, but will be back to New York in 2 weeks.

**Comment by linxu** [comment]
I've heard a lot about you in Suryani.
I've done the encryption and decryption project with you before.

**Comment by cwt9562** [comment]
I waiting for a demo project or a wiki for a long time.
Thx neo & linxu.
